BUG: use `dpss` instead of `slepian` in audiofileIO.py
note that this merely fixes an AttributeError,
`AttributeError: module 'scipy.signal' has no attribute 'slepian'`

There's a deeper issue with whether I'm calling `dpss` with the
right values, see
https://github.com/NickleDave/hybrid-vocal-classifier/issues/91