BUG: import `numpy.matlib` in features/tachibana.py
fixes `AttributeError: module 'numpy' has no attribute 'matlib'`

but note this module has been deprecated,
and we should switch to `np.tile`.
See https://github.com/NickleDave/hybrid-vocal-classifier/issues/92